### ISSUE TITLE
Can't Submit Form In Modal

### ISSUE THREAD

**Issue by lianapache** [kofile/react-modal#4]
``Submit`` event doesn't work in modal. I looked through other modal windows with forms we have created and they all use ``onClick`` instead of ``onSubmit``. But that wouldn't work in ``SignIn`` modal form since we use ``@kofile/react-form`` here which provides and validates ``formValues`` via ``onSubmit`` event. It seems that one of click events is blocking it.  Does anybody have an idea how to fix that?

**Comment by neezer** [comment]
Is there a wrapping `form` element?

**Comment by lianapache** [comment]
@neezer yes. Here's the  [code](https://github.com/kofile/ko-search-react/blob/master/src/App/screens/SignIn/View.js)
